version: "3"

tasks:
  build:
    cmds:
      - CGO_ENABLED=1 go build -o ./dist/app
  start:
    cmds:
      - go run main.go
  buf:generate:
    cmds:
      - rm -r -f ./gen
      - buf generate ../../protos/discord-status
  db:generate:
    cmds:
      - go generate ./ent
  vet:
    cmds:
      - go vet -v
  test:
    cmds:
      - go test -v ./...
  tidy:
    cmds:
      - go mod tidy
