services:
  bot:
    image: kbot/bot
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - 127.0.0.1:8600:8600
    networks:
      - kbot_dev

networks:
  kbot_dev:
    external: false
