apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: bot
  name: bot
  namespace: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: ghcr.io/kbot-discord/kbot:latest
          envFrom:
            - configMapRef:
                name: kbot-config
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
