apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  namespace: kbot
  labels:
    run: bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: bot
          image: ghcr.io/kbot-discord/bot:latest
          ports:
            - containerPort: 8600
            - containerPort: 8601
          envFrom:
            - configMapRef:
                name: kbot-env
          resources: {}
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /heartbeat
              port: 8600
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            httpGet:
              path: /heartbeat
              port: 8600
