// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Guild is the predicate function for guild builders.
type Guild func(*sql.Selector)

// Incident is the predicate function for incident builders.
type Incident func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)
