name: CI (Bot)

on:
  pull_request:
    paths:
      - "apps/bot/**"
      - "packages/**"
      - "!**/README.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: |
          yarn workspaces focus @kbotdev/apps @kbotdev/bot
          yarn turbo db:generate

      - name: Lint
        run: yarn turbo lint --filter=@kbotdev/bot

      - name: Run build
        run: yarn turbo build --filter=@kbotdev/bot

      - name: Run tests
        run: yarn turbo test --filter=@kbotdev/bot
