name: Build (Bot)

on:
  push:
    branches:
      - main
    paths:
      - "apps/bot/**"
      - "packages/**"
      - "protos/**"
      - "!**/README.md"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2.7.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          file: ./apps/bot/Dockerfile
          tags: ghcr.io/kbot-discord/bot:latest
