name: CI (Bot)

on:
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Install dependencies
        run: |
          pnpm install
          pnpm db:generate

      - name: Lint
        run: pnpm lint

      - name: Run build
        run: pnpm build

      - name: Run tests
        run: pnpm test
