name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Build
        run: yarn buf:generate

      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: src/rpc/gen

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: src/rpc/gen

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint --fix=false

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: src/rpc/gen

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Run tests
        run: yarn ci:test

      # - name: Save coverage report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nodejs-coverage
      #     path: coverage/

  # coverage:
  #   name: Coverage
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Project
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 2

  #     - name: Download NodeJS Unit Test Coverage report
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: nodejs-coverage
  #         path: coverage/

  #     - name: Codecov Upload
  #       uses: codecov/codecov-action@v3.1.1
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         fail_ci_if_error: true
