name: Deploy (Docs)

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm docs:build

      - name: Configure pages
        uses: actions/configure-pages@v4

      - name: Upload build
        uses: actions/upload-pages-artifact@v2
        with:
          path: apps/docs/docs/.vitepress/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
