name: Deploy (Docs)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "apps/docs/**"
      - "!**/README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Run build
        run: yarn turbo build --filter=@kbotdev/docs

      - name: Configure pages
        uses: actions/configure-pages@v3

      - name: Upload build
        uses: actions/upload-pages-artifact@v1
        with:
          path: apps/docs/docs/.vitepress/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
