name: CI (Docs)

on:
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install canvas dependencies
        run: sudo apt-get install \
          build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.5.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm docs:build
