name: CI (Discord-incident)

on:
  pull_request:
    paths:
      - "apps/discord-incident/**"
      - "protos/**"

defaults:
  run:
    working-directory: apps/discord-incident

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Run generate
        run: |
          task buf:generate
          task db:generate

      - name: Run build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
