name: CI (Proto)

on:
  pull_request:
    paths:
      - "protos/**"
      - "!**/README.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.0.0

      - name: Buf setup
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Buf lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: "protos"
