name: CI (Web)

on:
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/**"
      - "protos/**"
      - "!**/README.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn workspaces focus @kbotdev/apps @kbotdev/web

      - name: Sync
        run: yarn turbo sync --filter=@kbotdev/web

      - name: Build
        run: yarn turbo build --filter=@kbotdev/web

      - name: Check
        run: yarn turbo check --filter=@kbotdev/web

      - name: Lint
        run: yarn turbo lint --filter=@kbotdev/web
